### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by cgmccanna** [cgmccanna/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create a basic HTML Skeleton
- [x] Use CSS to set the background color of the body to green
- [x] Add an `img` element to the body with a `src` attribute of a relative path to the car icon
- [x] Edit the size of the car icon to fit correctly in the top left corner of the page
