### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by cgmccanna** [cgmccanna/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create an object named `car` which includes the direction the car is facing
- [x] Create 4 CSS rule sets which rotate the car each of the cardinal directions
- [x] Query the DOM for the img and assign it to the variable `$car`
- [x] Add a listener on the document for the `keydown` event and...
- [x] set the `car` direction property to the corresponding direction from the key that was pressed (ie. ArrowRight sets the value of the direction property to east)
- [x] at the end of the function, set the `$car` class name to the value of the direction property of the car object
- [x] Ensure transitions are smooth for turning the car
